### ISSUE TITLE
CRF usage

### ISSUE THREAD

**Issue by yassouali** [NVlabs/pacnet#10]
HI, first of all thank you for this amazing work,

I am working on a semantic segmentation problem, and using CRF as a post processing step, currently I am using pydensecrf, which is a CPU implementation, it would really speed things up if I can replace it with your version of CRF, the only problem is that I can't find all the parameters corresponding to this kernel defined in the fully connected CRF paper:

![](https://user-images.githubusercontent.com/45082182/64327059-5a314580-cfcb-11e9-86d7-7d8c3a24ee9e.png)

The kernel above is the one used in dense CRF,  and for seeing the provided example, when calling `create_YXRGB` I've seen that we only provide theta_alpha and theta_beta for the appearance kernel, but I can seem to find the parameters for the smoothness kernel and the weighting factors between the two kernels, I think i am missing something, I wonder how can I specify them.

Thanks.

**Comment by suhangpro** [comment]
Hi @yassouali, 

Really sorry that I just see this now that notified it's closed. The create_YXRGB function along won't sufficiently give you the exact kernel you want. You will need to have two kernels (as two calls to add_pairwise_kernel), one with create_YXRGB and another with create_postion_feats. The pairwise_weight argument can be used to model the weighting factors.

**Comment by yassouali** [comment]
No worries, I figured the issue got lost, Thank you very much for the answer!
