### ISSUE TITLE
some basic questions 

### ISSUE THREAD

**Issue by CalvinChuan** [NVlabs/pacnet#16]
Hi ,I’m really interested in this work.But as a newcomer in this field ,I got some basic questions after I read the code.

1:Why the channels of the guidance should be half of the input in the examples of the PacConv2d?
2:Are there any rules or the relations of the shape of feature(guide),K(Gussain kernel in this papre),   weight(convolution kernel)?

I’m sorry to bother you,I would appreciate it if you can answer me these questions or just help me get a better understanding of this great work. Thank you so much.

**Comment by suhangpro** [comment]
Hi @CalvinChuan ,  for a layer with input size B x C x H x W, the guidance input should be of size B x C_g x H x W, i.e. the batch size, height, width should be the same, but the depth can different. Using half C as C_g is simply a design choice that works well for our examples.

**Comment by suhangpro** [comment]
If you want to supply a pre-computed K to the layer (which can be efficient if it's reused more than once), it should be of size B x 1 x F x F x H x W, where F is the convolution filter size.

**Comment by CalvinChuan** [comment]
> If you want to supply a pre-computed K to the layer (which can be efficient if it's reused more than once), it should be of size B x 1 x F x F x H x W, where F is the convolution filter size.

Thankyou so much!!
