### ISSUE TITLE
Reason for scaling mask input

### ISSUE THREAD

**Issue by RSKothari** [NVlabs/pacnet#25]
Hello,

I observed that you've scaled the input to the mask over [here](https://github.com/NVlabs/pacnet/blob/12d52b6ebdd8e8afa0d2e54486ba77fbb3697a53/task_semanticSegmentation/fcn8s.py#L471). 

Is there any significance to this scaling operation?

**Comment by suhangpro** [comment]
This is to allow the model to train from a starting point close to the initialization. When the guidance feature is of a sufficiently small scale, its initial impact is quite small.
