### ISSUE TITLE
PAC_CRF step setting question

### ISSUE THREAD

**Issue by GITSHOHOKU** [NVlabs/pacnet#26]
Hi 

Should we set CRF step to 1 when training the whole model? And step to whatever we want when in the inference processing?

Because when I set CRF step to num>1, it will cause the in-place operation in the training process.

**Comment by suhangpro** [comment]
We train with the same number of iters used in inference (e.g. 5). What's the in-place operation you referred to?

**Comment by GITSHOHOKU** [comment]
> We train with the same number of iters used in inference (e.g. 5). What's the in-place operation you referred to?

The inplace_operation mentioned before points to the iteration manipulate value logQ , but it never happened again. Just a warning:
` RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).`
which doesn't affect the algorithm running.
Maybe it was just caused by Pytorch's inner mechanism. Now the training step is well. 
Thanks for your quick reply.
