### ISSUE TITLE
A question about updating the weight of the kernel

### ISSUE THREAD

**Issue by OmigaXm** [NVlabs/pacnet#29]
Thanks for sharing the code! But I still have a question.

In a pac layer, a kernel will be calculated according to the guide input. And the kernel will be calculated with the target input to get the output tensor. So when the network does the backpropagation, will the relationship between the weight of the kernel and the guide input change? Or the weight of the kernel is updated only because of the gradient?

I would be very grateful if you can give me some help. Thanks!

**Comment by suhangpro** [comment]
The backward pass of the layer will provide gradients on all three: a) weights (just like with regular conv2d), b) input features, and c) guide features. What we call _kernel_ can be considered as an intermediate variable that depends only on guide features.

**Comment by OmigaXm** [comment]
oh, I see. Thanks!
